### ISSUE TITLE
Fix lbry tv + redux issues around fs

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-redux#174]
It complained about the import fs, which I just removed for now in a hotfix. We probably need app vs web checking like we do on desktop, or some config in the rollup.

May be relevant https://github.com/webpack-contrib/css-loader/issues/447

https://github.com/rollup/rollup/issues/897

**Comment by seanyesmunt** [comment]
Closed with https://github.com/lbryio/lbry-desktop/pull/2716
