### ISSUE TITLE
make parseURI (URL) support all possible lbry urls

### ISSUE THREAD

**Issue by jessopb** [lbryio/lbry-redux#189]
Currently, parseURL errors on the following because it doesn't expect modifiers after /
  'lbry://@channel#2/stream:5'
  'lbry://@channel$2/stream#5'

**Comment by tzarebczan** [comment]
@jessopb this was fixed right?

**Comment by jessopb** [comment]
It looks like it - though it looks like the app doesn't respect $2 and such.
