### ISSUE TITLE
Add wallet encryption support (selectors, actions, and reducers)

### ISSUE THREAD

**Issue by skhameneh** [lbryio/lbry-redux#36]
## The Issue
Per https://github.com/lbryio/lbry-app/issues/762 and https://github.com/lbryio/lbry-app/issues/1097, wallet encryption support (selectors, actions, and reducers) needs to be added

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
@skhameneh how's it coming along?

**Comment by skhameneh** [comment]
Proceeding, will have it added this week. 😄
